### ISSUE TITLE
The arrow for opening the calendar is not on the right

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx.org-weirwood#10]
The date is moved too far up because the arrow is not on the right side.
![image](https://cloud.githubusercontent.com/assets/20114180/26316526/d3c0384c-3f14-11e7-997c-994cf43fd204.png)

**Comment by rassokhin-s** [comment]
It should be fixed now. Thanks.

**Comment by Starsonic007** [comment]
The calendar is now in the same row --> TEST OK 
![image](https://cloud.githubusercontent.com/assets/20114180/26647183/c32eb392-463e-11e7-9a80-fb99b36fe76f.png)
