### ISSUE TITLE
Allow Ranger Repositioning

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx.org-weirwood#3]
Users can drag an an arrow from a ranger location to a new grid location on the map. This will send a message to the API which will relate it to the rangers phones. They can use google maps to get to the right location.

**Comment by rassokhin-s** [comment]
<img width="357" alt="screenshot_stanislav 2017-04-04 15 33 17" src="https://cloud.githubusercontent.com/assets/2122991/24656683/116d7b58-194c-11e7-8084-c4c7728e56c0.png">
User can click on ranger, drag mouse and create an arrow. After submitting form "ghost" gray ranger appears at that point, which shows, where ranger should be.
