### ISSUE TITLE
Auto Switch To Alert

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx.org-weirwood#5]
Let's define the  **active audio stream** as the one currently being played. When an alert occurs, that is on a different stream than the active stream, the system automatically switches to the alerted guardian. This feature we call "auto switch to alert". We have an option that allows us to turn it on and off.

**Comment by rassokhin-s** [comment]
<img width="779" alt="screenshot_stanislav 2017-04-04 15 35 10" src="https://cloud.githubusercontent.com/assets/2122991/24656750/548f4542-194c-11e7-9529-66c449420fa0.png">
It is a "Event-driven" stream mode, which switches to newly appeared alerts automatically. When event is playing, blue pulse is animating around event marker.
