### ISSUE TITLE
Add Serial Play

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx.org-weirwood#6]
Let's define the  **active audio stream** as the one currently being played. The active audio stream has a different color from other states on the map. We can activate a serial play in set of any number of guardians. We can select any number of guardians which will get a different color on our map. Then we can press "serial play" and we listen to each guardian in turn for 30 seconds. When we get to the last guardian, we start over again. 

There's a button that allows us to stop and a button to pause serial play. The stop button deselects all guardians and non is on serial play. The pause button will keep all serial guardians but the currently active audio stream will not be replaced any time soon. 

In task #5 , we implemented the ability to auto-switch in the alert. This pauses serial play and sets the active audio stream to the alerted guardian.

**Comment by rassokhin-s** [comment]
<img width="905" alt="screenshot_stanislav 2017-04-04 15 37 55" src="https://cloud.githubusercontent.com/assets/2122991/24656838/b7d51b86-194c-11e7-82b2-2b8d2ef00734.png">
It's a Serial streaming mode which loads all guardians which are active and have coordinates and plays stream from each guardian for 30 seconds, then it switches to next guardian which has audio file in latest 3 minutes.
When any alert appears, it switches to guardian with that alert, plays this file and then gets back to serial playback.
There are two buttons to pause and stop series. Pause button stops switching between guardians, but plays current guardian for infinite time. Stop button stops both playback and switching.
